config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root 'home#index'
  get 'about', to: 'home#about', as: 'about'

  resources :users do
    resources :events
  end

  resources :events do
    resources :locations
    resources :guests
  end

  resources :locations do
    resources :rooms
  end

  match '/invite_guest', to: 'emails#send_mail', via: 'post'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: { large: "800x600#", medium: "300x200#", thumb: "100x100#" }, default_url: "/assets/images/missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :events
  has_many :guests

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def attending
    attending = []
    user_id = self.id
    guests = Guest.where(user_id: user_id)
    guests.each do |guest|
      event = guest.event
      attending.push(event)
    end
    return attending
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = current_user
    @events = @user.events.all
    @attending = @user.attending
  end
end

app/views/users/show.html.erb
<div class="row events">
  <div class='col-md-6'>
    <div class="panel panel-success">
      <div class="panel-heading">My Events <span class="pull-right add-event"><%= link_to "Add an event", new_user_event_path(current_user), class: "btn btn-primary" %></span></div>
      <ul class="list-group">
        <% if @events.any? %>
          <% @events.each do |event| %>
            <li class="list-group-item"><%=link_to event.title, user_event_path(current_user, event) %></li>
          <% end %>
        <% else %>
          <li class="list-group-item">I don't have any events planned yet!</li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-success">
      <div class="panel-heading">Events I'm going to</div>
        <ul class="list-group">
        <% if @attending.any? %>
          <% @attending.each do |event| %>
            <li class="list-group-item"><%=link_to event.title, user_event_path(event.user, event) %></li>
          <% end %>
        <% else %>
          <li class="list-group-item">I'm not invited to any events yet!</li>
        </ul>
    <% end %>
  </div>
</div>