config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root 'home#index'
  get 'about', to: 'home#about', as: 'about'

  resources :users do
    resources :events
  end

  resources :events do
    resources :locations
    resources :guests
  end

  resources :locations do
    resources :rooms
  end

  match '/invite_guest', to: 'emails#send_mail', via: 'post'

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_attached_file :photo, styles: {large: "800x800>", medium: "300x200#", thumb: "100x100#" }, default_url: "/assets/images/missing.jpg"

  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/


  has_many :guests
  has_many :locations
  has_many :rooms
  belongs_to :user


  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates :start_date, :presence => true
  validates :end_date, :presence => true

  def find_guest(user)
    event_id = self.id
    return Guest.where(user_id: user.id, event_id: event_id).first
  end

  def get_hotel_info(location)
    return  HTTParty.get("http://terminal2.expedia.com/x/hotels?hotelids=" + location.hotelid + "&dates=" + self.start_date.strftime("%Y-%m-%d") + "," + self.end_date.strftime("%Y-%m-%d") + "&apikey=" + "3FD8jYfm0LbZsxOcVZ66f89vByNPKXQB")
  end

  def has_room(guest)
    return guest.rooms.where(event_id: self.id).any?
  end

  def expedia_url(location)
    return 'https://www.expedia.com/' + location.city + '-Hotels-' + location.name.split(' ').join('-') + '.h' +    location.hotelid + '.Hotel-Information?chkin=' + self.start_date.strftime("%m").to_s + '%2F' + self.start_date.strftime("%d").to_s + '%2F' + self.start_date.strftime("%Y").to_s + '&chkout=' + self.end_date.strftime("%m").to_s + '%2F' + self.end_date.strftime("%d").to_s + '%2F' + self.end_date.strftime("%Y").to_s
  end

  def description_preview
    description.length > 300 ? description[0...300] : description
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @events = current_user.events.all
  end

  def new
    @event = Event.new
  end

  def create
    @user = current_user
    @event = Event.create(event_params)
    if @event.save
      @event.user = @user
      @event.save
      flash[:notice] = "Event successfully created"
      redirect_to new_event_location_path(@event)
    else
      render :new
    end
  end

  def show
    require 'httparty'
    @user = current_user
    @event = Event.find(params[:id])
    @start = @event.start_date.to_date.strftime("%m/%d/%Y")
    @end = @event.end_date.to_date.strftime("%m/%d/%Y")
    @locations = @event.locations
    @guests = []
    @event.guests.each do |guest|
      if guest.user
        user = guest.user
        @guests.push(user)
      end
    end
    @event_guest = current_user.guests.where(event_id: @event.id).first()
    #//look over here shannon!
    if @event_guest
      @prices = {}
      if !@event.has_room(@event_guest)
        @locations.each do |location|
          @prices[location.name] = {}
          response = @event.get_hotel_info(location)
          if response["HotelInfoList"]
            @prices[location.name]['price'] = "$" + response["HotelInfoList"]["HotelInfo"]["Price"]["TotalRate"]["Value"]
          else
            @prices[location.name]['price'] = "Unavailable"
          end
          if @prices[location.name]['price'] != "Unavailable"
            @prices[location.name]['query'] = @event.expedia_url(location)
          else
            @prices[location.name]['query'] = nil
          end
        end
      end
    end
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.infowindow location.name
      marker.lat location.latitude
      marker.lng location.longitude
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.new
    if @event.update(event_params)
      flash[:notice] = "Event successfully updated"
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :start_date, :end_date)
  end
end

app/views/events/_form.html.erb
<%= form_for [@user, @event], html: { multipart: true } do |f| %>

  <div class="field form-group">
    <%= f.label :title, class: "white" %>
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :description, class: "white" %>
    <%= f.text_area :description, rows: '10', autofocus: true, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :start_date, class: "white" %>
    <%= f.date_select :start_date, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :end_date, class: "white" %>
    <%= f.date_select :end_date, class: "form-control" %>



  <%= f.file_field :image, class: "white" %><br>
  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="container">
  <% if @events.any? %>
    <ul class="list-group">
      <% @events.each do |event| %>
        <li class="list-group-item"> <span class="title"><%= link_to event.title, event_path(event)%></span>
          <%= link_to "Delete", event_path(event), :data => {:confirm => "Are you sure?",
          :method => "delete"}, class: 'pull-right' %> </li>
      <% end %>
    </ul>
  <% else %>
    <h3>You have no events</h3>
  <% end %>
</div>

app/views/events/new.html.erb
<h1 class="white">Create Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="row">
  <h1 class="text-center"><%= @event.title %></h1>
  <br>
  <div class="col-md-6">
    <div class="well event-description">
      <span class="description-header">Event Description</span>
      <p>
        <%= @event.description_preview %>
        <% if @event.description_preview.length > 299  %>
        ... <button type="button" class="btn glyphicon glyphicon-plus" data-toggle="modal" data-target="#description-modal"></button>

          <!-- Modal -->
          <div id="description-modal" class="modal fade" role="dialog">
            <div class="modal-dialog">

              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title"><%= @event.title %></h4>
                </div>
                <div class="modal-body">
                  <p><%= @event.description %></p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>

            </div>
          </div>
        <% end %>
      </p>
    </div>
  </div>
  <div class="col-md-6">
    <div class="well">
      <ul class="event-details">
        <li><strong>Starts</strong>: <%= @event.start_date.strftime("%m/%d/%Y at %I:%M%p") %></li>
        <li><strong>Ends</strong>: <%= @event.end_date.strftime("%m/%d/%Y at %I:%M%p") %></li>
        <% if @event.locations.any? %>
          <li><strong>Located At</strong>: <%= @event.locations.first.name %></li>
        <% else %>
          <li>No location set</li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <h1>Guest locations</h1>
    <% if @event.locations.any? %>
      <ul class="list-group">
        <li class="list-group-item"id="map"></li>
      </ul>
    <% else %>
      No locations listed yet!
    <% end %>
  </div>

  <div class="col-md-4">
    <h1 class="white">Guest List</h1>
    <% if @guests.any? %>
    <div class="panel panel-success">
      <div class="panel-heading"><h3>Guests</h3></div>
      <ul class="list-group guest-list">
        <% @guests.each do |guest| %>
          <% if guest == @user && !@event.has_room(@event_guest) %>
            <li class="list-group-item">
              <%= guest.first_name %>
              <%= link_to "Add My Travel Plans", new_event_location_path(@event), class: "btn btn-success pull-right btn-xs", id: "add-button" %>
            </li>

          <% else %>
            <li class="list-group-item"> <%= guest.first_name %> </li>
          <% end %>
        <% end %>
    </div>
      <% else %>
      <p>No Guests Yet</p>
      </ul>
      <% end %>

    <div class="add-guest">
      <% if @user == @event.user %>
        <h3 class="text-center">Add Guest</h3>
        <div class="text-center">
          <%= form_tag invite_guest_path do %>
            <div class="row">
              <div class="form-group col-md-6">
                <%= text_field_tag 'name', nil, placeholder: 'Guest Name', class: 'form-control' %>
              </div>
              <div class="form-group col-md-6">
                <%= email_field_tag 'email', nil, placeholder: 'Guest Email', class: 'form-control' %>
              </div>
              <%=hidden_field_tag :event_id, params[:id] %>
              <%= submit_tag "Invite Guest", class: 'btn btn-default' %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>

<div class="row">
  <% if @locations.any? %>
  <button id="show-locations" class="btn btn-lg">Show Locations</button>
  <button id="hide-locations" class="btn btn-lg">Hide Locations</button>
    <div id="location-list">
      <% @locations.each do |location| %>
        <li class="list-group-item clearfix">
          <div class="col-xs-3 table-location-name">
            <%= location.name %>
          </div>
          <div class="col-xs-3 table-location-name">
            <button type="button" data-toggle="modal" data-target="#location-modal-<%=location.id%>" class="btn btn-success">Who's staying here?</button>

            <!-- Modal -->
            <div id="location-modal-<%=location.id%>" class="modal fade" role="dialog">
              <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h3 class="modal-title"><%= location.name %></h3>
                  </div>
                  <div class="modal-body">
                    <ul class="list-group">
                      <% location.guests.each do |guest| %>
                        <li class="list-group-item">
                          <span class="modal-guest-name">
                            <%= guest.user.first_name %> <%= guest.user.last_name %>
                          </span>
                          <span class="modal-room pull-right">
                            Room <%= guest.rooms.where(location_id: location.id).first().room_number %>
                          </span>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-6 locations-right-table">
            <% if @event_guest && !@event.has_room(@event_guest) %>
              <span class="estimated-price">Estimated Price for <%= distance_of_time_in_words(@event.start_date, @event.end_date) %>: <strong><%= @prices[location.name]['price'] %></strong></span>
              <% if @prices[location.name]['query'] %>
                <a href=<%= @prices[location.name]['query'] %> target="_blank"><button type="button" class="btn btn-primary pull-right">Book now</button></a>
              <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
    <% else %>
      <h3>You have no locations for this event</h3>
  </div>
  <% end %>
  <br>
</div>

<div class="find-hotels text-center">
  <h2>Don't see a place you like? Click here for a different hotel in the area!</h2>
    <span class="find-hotels-button">
      <button type="button" class="btn btn-primary" id="apiButton">Find Hotels</button>
    </span>
</div>

<br>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap();
  });

  $('#apiButton').click(function(){
    var loc = window.Locations = <%= (@locations.first.to_json.html_safe) %>;
    var start = window.Event = <%= (@start.to_json.html_safe) %>;
    var end = window.Event = <%= (@end.to_json.html_safe) %>;
    var address = loc["street"];
    var zip = loc["zip"];
    var url = "https://www.expedia.com/Hotel-Search?#destination=" + address + zip + "&startDate=" + start + "&endDate=" + end;
    window.open(url, "_blank");
  });
</script>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>