config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root 'home#index'
  get 'about', to: 'home#about', as: 'about'

  resources :users do
    resources :events
  end

  resources :events do
    resources :locations
    resources :guests
  end

  resources :locations do
    resources :rooms
  end

  match '/invite_guest', to: 'emails#send_mail', via: 'post'

end

app/views/layouts/_navbar.html.erb
<header class="nav-bar">
  <%= link_to 'Rsvp', root_path, class: "logo" %>
    <ul class="landing-tabs">
  <% if user_signed_in? %>
      <li><%=link_to "My Events", user_path(current_user)%></li>
      <li><%=link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <p>signed in as <%=current_user.first_name%><p>
  <% else %>
      <li><%= link_to "About", about_path %></li>
      <button class="btn btn-custom"><%= link_to "Sign in", new_user_session_path %> </button>
    </ul>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rsvp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
</head>
<div>
  <%= render "layouts/navbar" %>
  <body>
      <div class="container">
        <%= flash[:notice] %>
        <%= flash[:error] %>
        <%= yield %>
      </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RSVP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,800,300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
</head>
  <body>
      <%= render "layouts/navbar" %>
        <%= yield %>
        <%= flash[:notice] %>
        <%= flash[:error] %>
  </body>
</html>